start with editing post
Pablo-Mdz/OLINA-webpage pull request #33
Opened 2023-04-02 13:54 UTC by YuruBeDeniz

---
name: Pull Request Template
about: Template for creating new pull requests
---

## Summary

I started working with edit button, edit post card is shown when the edit button is clicked and user can cancel the event if cancel button is clicked. However, getting the post with axios.get(`/api/post/${id}`) with useEffect() is not working. Hence, axios.put(`/api/post/${id}`, requestBody) request is not working either. Haven't figured it out yet, I will continue working on it later.

## Related Issue

edit routes are not working.

## Type of Change

EditPost.jsx is added, 2 routes to post.route.js is added.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactoring (no new functionality, just code cleanup/refactoring)
- [ ] Documentation update

## Testing Steps

## Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/100470456/229357307-330e8e76-df71-4094-bf22-4813b5480995.png)

## Checklist

- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)

2023-04-02 14:24 UTC, antoniosaleme requested changes

2023-04-02 14:24 UTC, antoniosaleme commented on server/routes/post.routes.js
> +router.put("/id", (req, res) => {
also here

2023-04-02 14:24 UTC, antoniosaleme commented on server/routes/post.routes.js
> +router.get("/id", (req, res) => {
I think, it should be:

router.put("/:id", (req, res) => {

2023-04-02 15:12 UTC, antoniosaleme requested changes

2023-04-02 15:12 UTC, antoniosaleme commented on client/src/components/Blog/EditPostCard.jsx
> +  }, [])
I think you don't neet this one, you are already doing that on handleSubmit 🤔

2023-04-02 15:12 UTC, antoniosaleme commented on server/routes/post.routes.js
> +  Post.findByIdAndUpdate(req.params.postId, { post }, { new: true })
this one, should be something like this:
const { title, body } = req.body;
  Post.findByIdAndUpdate(req.params.id, { title, body }, { new: true })

2023-04-02 15:16 UTC, antoniosaleme requested changes

2023-04-02 15:16 UTC, antoniosaleme commented on client/src/components/Blog/EditPostCard.jsx
> +  const id = post._id;
what are you doing with this one? 👀

2023-04-02 18:10 UTC, antoniosaleme requested changes

2023-04-02 18:10 UTC, antoniosaleme commented on server/routes/post.routes.js
> +    .then(post => {
don't forget to populate:

 .populate('author')

2023-04-03 08:42 UTC, Pablo-Mdz approved these changes

2023-04-03 08:42 UTC, merged