Not found page
Pablo-Mdz/OLINA-webpage pull request #69
Opened 2023-04-17 15:21 UTC by Pablo-Mdz

## Description

I built the page not found using figma, but the letters look a bit big to me, please check it and if you like, approve the PR

- [x] New feature (non-breaking change which adds functionality)

## Screenshots 

<img width="1438" alt="Screenshot 2023-04-17 at 17 19 52" src="https://user-images.githubusercontent.com/80485682/232533035-be91e939-946a-45be-ab5d-9ab2f4ba52c7.png">

2023-04-18 22:14 UTC, antoniosaleme approved these changes
LGTM!

2023-04-18 22:25 UTC, antoniosaleme requested changes

2023-04-18 22:25 UTC, antoniosaleme commented on client/src/pages/NotFoundPage/NotFoundPage.jsx
> +        </a>
this one should be 266px x 31px(better use 32px)

2023-04-18 22:25 UTC, antoniosaleme commented on client/src/pages/NotFoundPage/NotFoundPage.jsx
> +        </p>
text should be text-4xl 
margin bottom should be mb-9 
line-hight should be leading-9

2023-04-20 20:34 UTC, Pablo-Mdz commented on client/src/pages/NotFoundPage/NotFoundPage.jsx
> +        </p>
with leading-10 is a bit better I think.

2023-04-20 20:47 UTC, merged